name: Android Auto Build
on:
  workflow_dispatch:
  push:
    branches:
      - dev
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
          distribution: temurin

      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: gen JKS File
        run: echo $ENCODED_KEYSTORE | base64 -di > app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}

      #      - name: Get commit SHA
      #        id: get_commit_sha
      #        run: 'echo ::set-output name=VERSION::-{GITHUB_SHA: 0: 6}'

      - name: Build APK with Gradle (DEV)
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          chmod +x gradlew
          ./gradlew build

        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Build APK with Gradle (MAIN)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew build
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Released APK
        uses: actions/upload-artifact@v2
        with:
          name: portalHook
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload APKs to Release Page
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            app/build/outputs/apk/release/app-release.apk